
networks:
  main:
    name: "itu-minitwit-network"

services:
  web:
    image: ${DOCKER_USERNAME}/minitwitimage
    ports:
      - "5000:5000"
  test:
    image: ${DOCKER_USERNAME}/minitwittestimage
    depends_on:
      - web